server:
  port: 7001
spring:
  application:
    name: CONFIGCLIENT
    rabbitmq:
    host: 192.168.111.131
    username: ems
    password: 123
    port: 5672
    virtual-host: /ems
management:
  endpoints:
    web:
      exposure:
        include: "*"
