server:
  port: 7002
spring:
  application:
    name: CONFIGCLIENT
    rabbitmq:
    host: lcoalhost
    username: ems
    password: 123
    port: 5672
    virtual-host: /ems
management:
  endpoints:
    web:
      exposure:
        include: "*"
